== NearMiss Web

== Purpose

This near-miss-engine is developed in context of the DMA <<../README.adoc#NearMiss,near-miss>> project.

The Purpose of the component is to expose a REST interface into the generated near-miss event data of the system.

== Build

The software is built as part of the parent maven build. To build this maven module separately just run `mvn package`
or similar.

When running the build use the SpringBoot default profile (application.properties) for standalone execution of the
tests.

== Usage

=== Run

The component has been designed to run in development mode (locally or within development environment). Or in a Docker
packaged mode.

Running development mode use the profile `dev`

Running in Docker use the profile `docker`

=== REST interface

When running the module browse to `http://localhost:8080` in order to access the API definition.

Also the API is defined in the <<./src/main/resources/near-miss.yml,near-miss.yml>> file.

[NOTE]
====
The configuration API has not been fully developed and should propably be deleted if not needed in the future.
====

== Back
Back to <<../README.adoc#NearMiss,near-miss>> parent modul