= GPS Simulator

== Purpose

This gps-simulator is developed in context of the DMA <<../README.adoc#NearMiss,near-miss>> project.

The Purpose of the component is to generate and expose GPS test data to the ais-simulator and pilot-plug-simulator.

== Build

The software is built as part of the parent maven build. To build this maven module separately just run `mvn package`
or similar.

When running the build use the SpringBoot default profile (application.properties) for standalone execution of the
tests.

== Usage

The component has been designed to run in development mode (locally or within development environment). Or in a Docker
packaged mode.

Running development mode use the profile `dev`

=== Run

Refer to the <<Dockerfile,Dockerfile>> to see how to run.

=== Configuration

The gps-simulator has several configurations.

Refer to the <<./src/main/java/dk/dma//nearmiss/gpssimulator/GpsSimulatorConfigurations.java,GpsSimulatorConfigurations.java>> class.

Also refer to the configurtion files:

* <<./src/main/java/resources/application.properties,application.properties>>
* <<./src/main/java/resources/application-dev.properties,application-dev.properties>>
* <<./src/main/java/resources/application-docker.properties,application-docker.properties>>

== Back
Back to <<../README.adoc#NearMiss,near-miss>> parent modul