= AIS Simulator

== Purpose

This ais-simulator is developed in context of the DMA <<../README.adoc#,near-miss>> project.

The Purpose of the component is to expose AIS test data to the pilot-plug-simulator.

== Build

The software is built as part of the parent maven build. To build this maven module separately just run `mvn package`
or similar.

When running the build use the SpringBoot default profile (application.properties) for standalone execution of the
tests.

== Usage

The component has been designed to run in development mode (locally or within development environment). Or in a Docker
packaged mode.

Running development mode use the profile `dev`

Running in Docker use the profile `docker`

== ToDO

=== Default Profile
Should be configured with no AIS data files. And the application should allow for this.

=== Document dependency to AisLib

https://github.com/dma-ais/AisLib

----
<dependency>
    <groupId>dk.dma.ais.lib</groupId>
    <artifactId>ais-lib-communication</artifactId>
    <version>2.4-SNAPSHOT</version>
</dependency>
----

== Back
Back to <<../README.adoc#NearMiss,near-miss>> parent modul