= AIS Simulator

== Purpose

This ais-simulator is developed in context of the DMA <<../README.adoc#NearMiss,near-miss>> project.

The Purpose of the component is to expose AIS test data to the <<../pilot-plug-simulator/README.adoc#Pilot-plug-simulator,pilot-plug-simulator>>.

== Build

The software is built as part of the parent maven build. To build this maven module separately just run `mvn package`
or similar.

When running the build use the SpringBoot default profile (application.properties) for standalone execution of the
tests.

== Usage

The component has been designed to run in development mode (locally or within development environment). Or in a Docker
packaged mode.

Running development mode use the profile `dev`

Running in Docker use the profile `docker`

=== Run

Refer to the link:Dockerfile[Dockerfile] to see how to run.

=== Configuration

The ais-simulator has several configurations.

Refer to the link:src/main/java/dk/dma/nearmiss/aissimulator/AisDataReaderConfiguration.java[AisDataReaderConfiguration.java] class.

Also refer to the configurtion files:

* link:src/main/resources/application.properties[application.properties]
* link:src/main/resources/application-dev.properties[application-dev.properties]
* link:src/main/resources/application-docker.properties[application-docker.properties]

=== Dependency to AisLib

This module does need AisLib to have been cloned from GitHub and built locally.

https://github.com/dma-ais/AisLib

----
<dependency>
    <groupId>dk.dma.ais.lib</groupId>
    <artifactId>ais-lib-communication</artifactId>
    <version>2.4-SNAPSHOT</version>
</dependency>
----

== Back
Back to <<../README.adoc#NearMiss,near-miss>> parent module.
